#                             NUMPY
#                        FreeCodeCamp.org

In [ ]:
A = [1,2,3]
B = [4,5,6]
C = A + B
# C = A - B   # this will raise an error because list does not support element-wise subtraction
print(C)

import numpy as np
nA = np.array([1,2,3])
nB = np.array([4,5,6])
nC = nA + nB
print(nC)

# list does not support element-wise addition, it concatenates the lists instead
# numpy arrays support element-wise addition, it adds the corresponding elements together

Numpy vs List  : 
Numpy faster

In [ ]:
#list
a = [1,3,5]
b = [1,2,3]
# print(a*b)   # error

#numpy array
import numpy as np
a = np.array([1,3,5])
b = np.array([1,2,3])
print(a*b)           # element wise multiplication

Applications of numpy

1. Mathematics(MATLAB replacement)     but scifi better
2. Plotting(Matplotlib)
3. Backend(Pandas,Connect 4, store png images etc)
4. Machine Learning  


In [ ]:
a = np.array([1,2,3,4])
print(a)
print()
b = np.array([[1,2,3,4],[5,6,7,8]])
print(b)

print()

#Dimension
print("Dimension of a:",a.ndim)
print("Dimension of b:",b.ndim)

#Shape      rows and columns
print("Shape of a:",a.shape)
print("Shape of b:",b.shape)

#Get type
print("Type of a:",a.dtype)
print("Type of b:",type(b))

In [ ]:
c = np.array([1,2,3,4])
# c = np.array([1,2,3,4],dtype = int16)

print(c.itemsize)   # bytes per element
print(c.size)      # total number of elements
print(c.nbytes)  # total bytes consumed by the elements of the array
print(c.size*c.itemsize) # total bytes consumed by the elements of the array

# Accessing or changing specific elements,rowws,columns etc


In [ ]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print("a:",a)
# get specific element [r,c]
print("a[1,5] = ",a[1,5])

# get specific row
print("First row: ",a[0,:])  # first row

# get specific column
print("Third column: ",a[:,2])  # third column

# getting a little fancy [startindex:endindex:stepsize]
print("Specific: ",a[0,1:6:2])  # first row, from index 1 to 5, step size 2

#changing value
a[1,5] = 20
print("a:",a)

#changing a whole row
a[0,:] = 1
print("a:",a)
a[0,:] = [1,2,3,4,5,6,7]
print("a:",a)

In [ ]:
#3D array
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print("b:",b)
print("Dimension of b:",b.ndim)
print("Shape of b:",b.shape)

In [ ]:
# Initialize different types of arrays

# all zeros
#z = np.zeros((2,3))
z = np.zeros((2,3),dtype=int)
print("Zeros:\n",z)

# all ones
r = np.ones((4,2),dtype=int)
print("Ones:\n",r)

# any other number
f = np.full((2,3),7)     # 2x2 array with all elements as 7
print("Full:\n",f)

a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print("a:",a)
d = np.full_like(a,5)   # array of same shape as a with all values as 5
print("d:\n",d)


# Initialize empty array


np.nan means "Not a Number"
It is used to represent missing or invalid numerical values

a = np.array([1, 2, np.nan, 4])

print("np.nan example:")
print(a)


#   
#   
np.full()

np.full(shape, value)
Creates an array and fills every position
with the SAME value

b = np.full((2,3), 7)

print("\nnp.full() example:")
print(b)



# np.full() with np.nan
Creates an array where every value is NaN
Common in data science for missing data

c = np.full((2,2), np.nan)

print("\nnp.full() with np.nan:")
print(c)




# np.empty()

Creates an array without initializing values
The values are random garbage values already in memory
Faster than zeros/full because memory is not cleared

d = np.empty((2,2))

print("\nnp.empty() example:")
print(d)

In [ ]:

# Initialize empty array

e = np.empty((3,4))   # uninitialized array of shape 3x4
print("Empty:\n",e)


f = np.full((3,4),np.nan)   # array of shape 3x4 with all values as NaN
print("Full with NaN:\n",f)


In [ ]:
# Random Numbers

r = np.random.rand(2,3)  # uniform distribution between 0 and 1
print("Random:\n",r)

r = np.random.random_sample(a.shape) # array of same shape as a with random values
print("Random Sample \"a\":\n",r)

# random integar
r = np.random.randint(1,100,size=(2,3)) # random integers between 1 and 100
print("Random Integers:\n",r)

r = np.random.randint(100,size=(2,3)) # random integers between 0 and 100
print("Random Integers:\n",r)

# Identity matrix
i = np.identity(4)
print("Identity:\n",i)

In [ ]:
# Repeat an array

arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3,axis=0) # repeat 3 times along rows
print("Repeat:\n",r1)

r1 = np.repeat(arr,3,axis=1) # repeat 3 times along columns
print("Repeat:\n",r1)


In [ ]:
""" 
    1 1 1 1 1
    1 0 0 0 1
    1 0 9 0 1
    1 0 0 0 1
    1 1 1 1 1
"""

output = np.ones((5,5),dtype = int)
output[1:4,1:4] = 0     # rows 1 to 3 and columns 1 to 3 will be set to 0
output[2,2] = 9
print("Output:\n",output)

# Copy an entire array

In [ ]:
# Copying elements
a = np.array([1,2,3])
b = a
b[0] = 100
print("b:",b)
print("a:",a)   # a is also changed because b is just a reference to a


# To avoid this we use copy()
a = np.array([1,2,3])
b = a.copy()
b[0] = 100
print("b:",b)
print("a:",a)



# Mathematics

In [ ]:
a = np.array([1,2,3,4])

print("a:",a)
print("a+2:",a+2)
print("a-2:",a-2)
print("a*2:",a*2)
print("a/2:",a/2)
print("a%2:",a%2)         # modulus of each element
print("a**2:",a**2)         # square each element
print("sqrt(a):",np.sqrt(a))
print("sin(a):",np.sin(a))


# normal list operations do not support element-wise operations, they will raise an error
# so we have to use numpy arrays for element-wise operations




# Linear Algebra

In [ ]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("a:\n",a)
b = np.array([[3,6,2],[1,5,7],[4,9,8]])
print("b:\n",b)

print(a*b)                  # element wise multiplication   (This is NOT Matrix Multiplication)

# Matrix Multiplication
a = np.ones((2,3))
b = np.full((3,2),2)
print("a:\n",a)
print("b:\n",b)
# print(a*b)         # element wise multiplication not possible because of different shapes
d = np.matmul(a,b)  # matrix multiplication
print("Matrix Multiplication:\n",d)



# Determinant
a = np.array([[1,2],[3,4]])
det = np.linalg.det(a)
print("Determinant:",det)



# Trace
a = np.array([[1,2],[3,4]])
trace = np.trace(a)
print("Trace:",trace)

# Singular Value Decomposition

# Eigenvalues and Eigenvectors

# Matrix Rank

# Inverse

# QR Decomposition




# Statistics

In [ ]:
stats = np.array([[1,2,3,],[4,5,6]])
a = np.min(stats)   # minimum value in the array
print("Minimum value:",a)

a = np.max(stats)   # maximum value in the array
print("Maximum value:",a)

a = np.min(stats,axis=0)   # minimum value in each column
print("Minimum value column wise:",a)

a = np.max(stats,axis=1)   # maximum value in each row
print("Maximum value row wise:",a)

a = np.sum(stats)   # sum of all elements
print("Sum of all elements:",a)



In [ ]:
# Reshaping an array
a = np.array([[1,2,3,4],[5,6,7,8]])
print("a:",a)

b = a.reshape((8,1))
# b = a.reshape((9,1))    # cannot reshape array of size 8 into shape (9,1)
print("b:",b)

b = a.reshape((4,2))
print("b:",b)

In [29]:
# Vertically Stacking Vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])
v3 = np.vstack([v1,v2,v1])
print("Vertical Stack:\n",v3)


# Horizontally Stacking Vectors
h1 = np.array([[1,2,3,4],[5,6,7,8]])
h2 = np.array([[9,10],[11,12]])
h3 = np.hstack([h1,h2])
print("Horizontal Stack:\n",h3)

Vertical Stack:
 [[1 2 3 4]
 [5 6 7 8]
 [1 2 3 4]]
Horizontal Stack:
 [[ 1  2  3  4  9 10]
 [ 5  6  7  8 11 12]]


# Miscellaneous

Load Data from File

In [ ]:
filedata = np.genfromtxt('data.txt',delimiter=',')
# filedata.astype('int32')       # sudhu copy banay
filedata = filedata.astype('int32')
filedata 

Boolean Masking and Advanced Indexing

In [ ]:
print(filedata > 5)   # boolean array

print(filedata[filedata > 5])  # values greater than 5


In [ ]:
# You can index with a list of indexes in Numpy arrays
a = np.array([10,20,30,40,50,60,70,80,90])
indexes = a[[1,3,5]]  # get values at index 1, 3 and 5
print("Indexes:",indexes)

In [ ]:
print(np.all(filedata > 2,axis=0))        # check if all values of a column are greater than 2
print(np.any(filedata > 7,axis=0))        # check if any value of a column is greater than 2



# row er jonno axis=1, column er jonno axis=0

((filedata > 3) & (filedata < 8))       # boolean array with values between 3 and 8